version: "3.5"
services:
  jenkins:
    container_name: jenkins2
    image: jenkins/jenkins:lts
    networks:
      - cloudacademylabs
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://socat:2375
    depends_on:
      - socat
  socat:
    container_name: socat
    #image: socat-ca:latest
    image: alpine/socat:latest
    networks:
      - cloudacademylabs
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
  postgres:
    container_name: postgres
    #image: postgres-ca:latest
    image: postgres:9.6
    networks:
      - cloudacademylabs
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  sonarqube:
    container_name: sonarqube2
    #image: sonarqube-ca:latest
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - cloudacademylabs
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres

networks:
  cloudacademylabs:
    name: cloudacademylabs
